### ISSUE TITLE
vhosts.sls not working

### ISSUE THREAD

**Issue by leonhedding** [saltstack-formulas/tomcat-formula#106]
I needed to edit vhosts.sls to get it working. It would never apply any vhost settings otherwise.

I added the bolded line below to get it working.

tomcat 300_server_xml:
  file.accumulated:
    **- name: 300_server_xml**

**Comment by myii** [comment]
Thanks for this report, @leonhedding. Can you share the output you were getting beforehand and the Salt versions report?

**Comment by leonhedding** [comment]
The vhosts settings were never applied. The server was getting the default site settings as if I had not configured anything for vhosts. All the other accumulated settings have the added -name: 500_server.xml etc settings so I tried it and now the vhosts settings are applied.

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.27.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by myii** [comment]
@leonhedding This should be fixed now after the merge of #107.  Feel free to reopen this if there's still a problem.
