### ISSUE TITLE
Centos: package not found

### ISSUE THREAD

**Issue by lookingcloudy** [saltstack-formulas/tomcat-formula#20]
----------
          ID: tomcat7
    Function: pkg.installed
      Result: False
     Comment: The following package(s) were not found, and no possible matches were found in the package db: tomcat7
     Changes:   
----------

**Comment by cubranic** [comment]
Why do you hardcode package and service names to be `{{ tomcat.name }}{{ tomcat.version }}` all over the place? (I haven't seen `tomcat.name` used once without being concatenated with `version`.) Couldn't this be set once in `map.jinja`, according to the platform?

This would make the code more readable and simplify supporting platforms that don't embed the version in the package name, as RHEL.

**Comment by fintanmm** [comment]
I'm closing this for now. PR #30 should fix it.
