### ISSUE TITLE
JAVA option handling is suboptimal

### ISSUE THREAD

**Issue by babilen** [saltstack-formulas/tomcat-formula#24]
This formula really shouldn't require *global* java keys in the pillar and the `file.append` approach is  quite horrible as it adds new lines whenever an option changes *and* also doesn't allow users to set additional options.

It would, IMHO, be much better to simply allow users to set JAVA_OPTS in their entirety in the pillar with a sensible default.

**Comment by puneetk** [comment]
sweet , send over pull with recommended changed

**Comment by fintanmm** [comment]
I'm going to close this as #30 deals with this issue.
