### ISSUE TITLE
Tomcat takes very long to start up on a fresh Ubuntu VM

### ISSUE THREAD

**Issue by lewandom** [saltstack-formulas/tomcat-formula#25]
When deploying Tomcat server on a fresh VM using automation just after the boot, it takes very long for the service to start accepting requests (> 3 mins average). Per https://www.digitalocean.com/community/questions/fresh-tomcat-takes-loong-time-to-start-up, this is a low entropy problem which could be mitigated by installing haveged package. I think the formula could be enhanced by adding this package installation when running on Ubuntu.

**Comment by gravyboat** [comment]
If you would like feel free to create a PR adding this (preferably in a different state, or toggled via the pillar) as it sounds reasonable to me.

**Comment by lewandom** [comment]
I created the PR. Installing in this state as I feel we need a strict dependency. By default off, can be enabled with "tomcat:with_haveged" pillar flag. For now only for Ubuntu, not sure if needed on other systems as well.
