### ISSUE TITLE
Arch derivative: tomcat.manager state rendering error

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#67]
State **tomcat.manager** fails on Archlinux derivatives.

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:tomcat.manager' failed: Jinja variable 'dict object' has no attribute 'manager_pkg'
```

**Comment by noelmcloughlin** [comment]
Salt grains.os does not recognise Manjaro as being archlinux derivative although it is based on 
 archlinux packages.
```
# on archlinux tomcat manager is already in tomcat package
 {% if grains.os != 'Arch' %}
  {{ tomcat.manager_pkg }}:
    pkg.installed:
      - require:
        - pkg: tomcat
  {% endif %}
```
The following clause could be added.
```
      # except distros using archlinux packages
      - unless: test -f /usr/bin/pacman
```

**Comment by aboe76** [comment]
@noelmcloughlin could you open an issue on https://github.com/saltstack/salt about manjaro...

**Comment by noelmcloughlin** [comment]
@aboe76  I changed to {%  if grains.os_family != 'Arch' %} and that works for manjaro!!!

**Comment by aboe76** [comment]
@noelmcloughlin it's thinking manjaro uses sysv init instead of systemd, this is likely because it couldn't find out which init system to use... should be fixed if manjaro is assigned os_family Arch.

**Comment by aboe76** [comment]
Salt should detect Manjaro: https://github.com/saltstack/salt/pull/27841

**Comment by noelmcloughlin** [comment]
Regarding #68 will investigate.

The solution for #67 is checking `grain.os_family` instead of 'grain.os' and tested successfully on Manjaro:- [tomcat_manjaro_testresult.log.txt](https://github.com/saltstack-formulas/tomcat-formula/files/1347207/tomcat_manjaro_testresult.log.txt)
