### ISSUE TITLE
RFE: Abstract MacOS/Darwin from Tomcat vendor

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#77]
The Tomcat formula only supports Homebrew as software vendor of Tomcat.  Need to introduce support for **other software vendors** of Tomcat for MacOS/Darwin.

osmap.yaml
```
+  #Not used on Arch
 +  manager_pkg:
 +MacOS:
 +  {% set darwin_javahome = salt['cmd.run']('/usr/libexec/java_home') if grains.os =='MacOS' else {} %}
 +  service: homebrew.mxcl.tomcat`
```

**Comment by noelmcloughlin** [comment]
@johnkeates  Do you know of any other Tomcat vendor for this formula on MacOS?  AFAIK both  homebrew and tomcat.org are effectively the same vendor / same tarball.  There may be value in adding *general* support for downloading binaries from tomcat.org across all OS, but not as MacOS specific thing.  I'm trying to figure out what is required for this formula. 

```
$ brew install tomcat
==> Downloading https://www.apache.org/dyn/closer.cgi?path=tomcat/tomcat-8/v8.5.27/bin/apache-tomcat-8.5.27.tar.gz
==> Best Mirror http://mirrors.whoishostingthis.com/apache/tomcat/tomcat-8/v8.5.27/bin/apache-tomcat-8.5.27.tar.gz
######################################################################## 100.0%
==> Caveats
To have launchd start tomcat now and restart at login:
  brew services start tomcat
Or, if you don't want/need a background service you can just run:
  catalina run
==> Summary
🍺  /usr/local/Cellar/tomcat/8.5.27: 635 files, 12.9MB, built in 6 seconds
```

But tomcat.org publishes the same file / same tarball: 

`http://ftp.heanet.ie/mirrors/www.apache.org/dist/tomcat/tomcat-8/v8.5.27/bin/embed/apache-tomcat-8.5.27-embed.tar.gz`

**Comment by johnkeates** [comment]
They are probably the same tarball, but brew tends to install in special Cellar locations whereas tomcat has defaults in /usr/local/ AFAIK. I guess the difference can be detected, maybe we have a defaults or lookup that at least has the default brew paths as well as the default 'local' paths, and if someone wants to use something else, they are on their own.

**Comment by noelmcloughlin** [comment]
Thanks @johnkeates 
The correct approach would appear to be introduction of an "use_upstream_repo: y/n"  feature for any OS.  Looking at SLS structure, etc, I think that might be sensible here.  Handling tarball is well known pattern so should work fine, by default distro package would be used (i.e. zypp,yum,homebrew, etc)??

**Comment by noelmcloughlin** [comment]
I no longer have MacOS.  This formula does not support non-homebrew Tomcat on Macos.
However, I no longer have MacOS so cannot do this.
If someone needs alternative to homebrew they must raise PR.
https://github.com/saltstack-formulas/tomcat-formula/pull/71/files#r142819969
