### ISSUE TITLE
 Tomcat8 issues on Ubuntu/JDK10

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/tomcat-formula#97]
https://bugs.launchpad.net/ubuntu/+source/tomcat8/+bug/1586054

**Comment by noelmcloughlin** [comment]
Maybe tomcat8 dont work with openjdk.   

And catalina logs reports  missing directory?
```
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]```

The directory `/var/lib/tomcat8/` does not contain any `common` file or directory.

**Comment by noelmcloughlin** [comment]
Apparently symlinks are not setup on ubuntu
``` 
    ln -s /var/lib/tomcat8/common $CATALINA_HOME/common && \
    ln -s /var/lib/tomcat8/server $CATALINA_HOME/server && \
    ln -s /var/lib/tomcat8/shared $CATALINA_HOME/shared && \
    ln -s /etc/tomcat8 $CATALINA_HOME/conf && \
    mkdir $CATALINA_HOME/temp
```

**Comment by javierbertoli** [comment]
Actually, I think `openjdk-10-jre` is enough? I'm not sure the whole SDK is necessary?

**Comment by noelmcloughlin** [comment]
I used vagrant `ubuntu/bionic64` which has java10.  I got tomcat working using `sun-java-formula` to install java8.

**Comment by noelmcloughlin** [comment]
Maybe Tomcat8 only works with Java8 or earlier.
https://stackoverflow.com/questions/52644943/tomcat-8-stopped-working-after-ubuntu-update

**Comment by noelmcloughlin** [comment]
Tomcat8 is not working on Ubuntu18.04. The `/etc/init.d/tomcat8` service falls over. Default java is jdk-11-headless

**Comment by noelmcloughlin** [comment]
The only solution I see is using Tomcat9

**Comment by chrisco484** [comment]
> The only solution I see is using Tomcat9

We switched many of our Tomcat instances from Tomcat 7 to Tomcat 9 a few months back and everything worked as expected (even better because there's some new features that Chrome now requires that aren't even possible pre Tomcat 9).

So moving to Tomcat 9 gets a +1 from me!

**Comment by noelmcloughlin** [comment]
Thanks, I merged that PR so issue is resolved.

**Comment by noelmcloughlin** [comment]
#119
